### ISSUE TITLE
Using the Bot to inform players of roleplay.

### ISSUE THREAD

**Issue by Yuzurukyun** [Chrezm/DROBot#3]
There are two ideas to this concept.

One, we can use the bot to DM those who have "RP Active" in their roles to get notified regarding the announcement of the RP  followed by the announcement itself copy-pasted from `#rp-announcements`.
This is prone to spam and abuse, however, which is why we should have a condition check before it sends out to people's DMs.

Furthermore, the other idea is that the bot should be able to store dates/times of an RP so that people would be reminded that the deadline for signups/RP date is approaching.

**Comment by Chrezm** [comment]
Added in #4
